[package]
name = "dslnews"
version = "1.0.0"
edition = "2018"

[dependencies]
inquire = "0.2.1"
reqwest = "*"
select = "*"
open = "1"
tokio = { version = "1", features = ["full"] }
clap = { version = "3.1.18", features = ["derive"] }
textwrap = "0.15"

